"""Feature normalization for the 47-feature scoring system.

Provides scale factors and conversion utilities between raw-weight space
and normalized-weight space.  The mathematical trick:

    f_norm = f_raw / scale
    score  = w_norm · f_norm = (w_norm / scale) · f_raw

So at runtime we pre-divide weights by scales and dot with raw features,
giving zero overhead while keeping weights in a human-readable normalized
space where each feature contributes proportionally.
"""

from __future__ import annotations

import numpy as np

# Scale factors for all 47 features.
# Each value represents the p99 of that feature observed in 500 games
# (SmartAgent vs mixed opponents), clamped to >= 1.0.
# Generated by scripts/collect_feature_stats.py.
FEATURE_SCALES_47 = np.array([
    # 0-34: base features
    1.0,    # completed_sequences
    8.0,    # four_in_a_row
    16.0,   # three_in_a_row
    27.0,   # two_in_a_row
    1.0,    # opp_completed_sequences
    8.0,    # opp_four_in_a_row
    16.0,   # opp_three_in_a_row
    27.0,   # chips_on_board
    27.0,   # opp_chips_on_board
    15.0,   # center_control
    4.0,    # corner_adjacency
    2.0,    # hand_pairs
    1.0,    # two_eyed_jacks_in_hand
    2.0,    # one_eyed_jacks_in_hand
    1.0,    # dead_cards_in_hand
    74.0,   # shared_line_potential
    128.0,  # blocked_lines
    7.0,    # guaranteed_positions
    8.0,    # viable_four_in_a_row
    16.0,   # viable_three_in_a_row
    3.0,    # opp_blockable_four
    7.0,    # opp_unblockable_four
    10.0,   # fork_count
    1.0,    # dead_positions_for_us
    1.0,    # dead_lines
    1.0,    # opp_dead_lines
    1.0,    # card_monopoly_count
    9.6,    # sequence_proximity
    25.2,   # position_line_score
    5.0,    # anchor_overlap_count
    1.0,    # chip_clustering
    1.0,    # early_jack_usage_penalty
    1.9,    # jack_save_value
    67.0,   # viable_line_connectivity
    229.0,  # weighted_blocking
    # 35-46: expert features
    16.0,   # silent_threat_count
    3.0,    # corner_line_progress
    1.0,    # phantom_threat_count
    2.8,    # opp_threat_reachability
    12.0,   # permanent_disruption_potential
    95.0,   # hand_flexibility
    5.0,    # race_advantage
    6.0,    # multi_block_value
    1.0,    # key_card_count
    8.0,    # urgency_clock
    23.1,   # alive_line_position_score
    3.0,    # open_ended_three_count
], dtype=np.float64)


def to_normalized_space(
    w_raw: np.ndarray,
    scales: np.ndarray | None = None,
) -> np.ndarray:
    """Convert raw weights to normalized space: w_norm = w_raw * scales."""
    if scales is None:
        scales = FEATURE_SCALES_47[: len(w_raw)]
    return w_raw * scales


def to_raw_space(
    w_norm: np.ndarray,
    scales: np.ndarray | None = None,
) -> np.ndarray:
    """Convert normalized weights to raw space: w_raw = w_norm / scales."""
    if scales is None:
        scales = FEATURE_SCALES_47[: len(w_norm)]
    return w_norm / scales
